# Application name
spring.application.name=NompumeleloNzama

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:enviro365db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.defer-datasource-initialization=true

# H2 Console (lets you view the database in a browser while app runs)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server port
server.port=8080